services:
  app:
    build:
      context: .
      target: dev
    command: bin/dev -b 0.0.0.0
    volumes:
      - .:/rails
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundler: